language: node_js
node_js:
  - lts/dubnium
  - stable

sudo: false

env:
  global:
    - COVERALLS_PARALLEL=true

cache:
  yarn: true

before_install:
  - npm i -g yarn greenkeeper-lockfile
  - greenkeeper-lockfile-update
install: yarn install --check-files --ignore-engines
script:
  - yarn run tslint
  - if [[ $GH_TOKEN ]]; then yarn run build && semantic-release --dry-run --branch $TRAVIS_BRANCH; else yarn run build --noEmit; fi;
  - yarn test --forbid-pending
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
  - Test
  - name: Release
    if: branch = master AND type = push AND (NOT tag IS present)

jobs:
  include:
    - stage: Release
      node_js: stable
      before_install: npm i -g yarn
      before_script: yarn run build
      script: semantic-release
      after_success: []
      after_script: []

notifications:
  webhooks: https://coveralls.io/webhook
